name: text_scroll
description: TextScroll Flutter widget adds text auto-scrolling functionality (marquee text).
version: 0.2.0
repository: https://github.com/yurii-khi/text_scroll

environment:
  sdk: ">3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_ui: any
